version: "3.7"

networks:
  default:
    name: autods

services:
  app:
    container_name: autods_app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.dev
    networks:
      - default

  postgres:
    image: postgres:14.2-alpine
    container_name: autods_postgres
    restart: unless-stopped
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    volumes:
      - ./local/postgres/data:/var/lib/postgresql/data
    networks:
      - default
